# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimuKPISummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_name', models.CharField(max_length=100)),
                ('kpi_value', models.DecimalField(decimal_places=6, default=0.0, max_digits=18)),
                ('kpi_datetime', models.DateTimeField(verbose_name='kpi date')),
            ],
        ),
        migrations.CreateModel(
            name='SimuSummary',
            fields=[
                ('test_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('data_start_time', models.DateTimeField(verbose_name='data start time')),
                ('data_end_time', models.DateTimeField(verbose_name='data end time')),
                ('created_at', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='simukpisummary',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.SimuSummary'),
        ),
    ]
